name: Build and Test Java Spring Boot Application
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with maven
        run: mvn -B package --file pom.xml
      - name: Deploy tu github pages
        uses: actions/deploy-pages@v4